### ISSUE TITLE
Support JavaConversions in scala-library-jribble

### ISSUE THREAD

**Issue by stephenh** [scalagwt/scalagwt-scala#9]
It is not currently in scala-library-jribble.jar.

**Comment by gkossakowski** [comment]
Fixed by various changes that got merged into scalagwt-scala project. See [scala/scalagwt-sample#24](http://github.com/scalagwt/scalagwt-sample/pull/24) for details.

Note: I tried linking to scala/scalagwt-sample#24 using GFM syntax but it doesn't work.
